# Generated by Django 6.0 on 2026-02-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_booking_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Guest', max_length=100),
            preserve_default=False,
        ),
    ]
